import 'package:get/get.dart';

class Strings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'powered_by': 'Powered by',
          'mobile_number': 'Mobile number',
          'enter_mobile_number': 'Enter mobile number',
          'enter_valid_mobile_number': 'Enter valid mobile number',
          'send_otp': 'Send OTP',
          'by_continuing_you_agree_to_our': 'By continuing, you agree to our',
          'privacy_policy': 'Privacy Policy',
          'and': 'And',
          'terms_and_conditions': 'Terms & Conditions',
          'enter_otp_sent_to_this_mobile_number':
              'Enter OTP sent to this mobile number',
          'submit': 'Submit',
          'resend_otp_in': 'Resend OTP in',
          'resend_otp': 'Resend OTP',
          'punch_in': 'Punch In',
          'punch_out': 'Punch Out',
          'attendance': 'Attendance',
          'regularise': 'Regularise',
          'leaves': 'Leaves',
          'claims': 'Claims',
          'holidays': 'Holidays',
          'reimbursement': 'Reimbursement',
          'documents': 'Documents',
          'faqs': 'FAQs',
          'attendance_activity': 'Attendance Activity',
          'last_seven_days': 'Last 7 days',
          'home': 'Home',
          'notifications': 'Notifications',
          'settings': 'Settings',
          'profile': 'Profile',
          'logout': 'Logout',
          'please_wait': 'Please wait...',
          'ok': 'OK',
          'attendance_captured_successfully':
              'Attendance captured successfully',
          'time_to_mark_your_attendance': 'Time to mark your attendance',
          'punch_in_time': 'Punch in time',
          'punch_out_time': 'Punch out time',
          'click_here': 'Click here',
          'quick_actions': 'Quick Actions',
          'annual_balance_leaves': 'Annual Balance Leaves - ',
          'days': 'Days',
          'select_billing_cycle': 'Select Attendance Cycle',
          'paid_leave': 'Paid leave',
          'pending': 'Pending',
          'approved': 'Approved',
          'rejected': 'Rejected',
          'all': 'All',
          'apply_leave': 'Apply Leave',
          'leave_type': 'Leave type',
          'select_leave': 'Select Leave',
          'from_date': 'From Date',
          'select_date': 'Select Date',
          'to_date': 'To Date',
          'reason': 'Reason',
          'reimbursements': 'Reimbursements',
          'request_reimbursement': 'Request reimbursement',
          'types_of_claim': 'Types of Claim',
          'sub_types_of_claim': 'Sub Types of Claim',
          'select_claim_type': 'Select Claim Type',
          'receipt_no': 'Receipt no.',
          'amount': 'Amount',
          'applying_to': 'Applying to',
          'remarks': 'Remarks',
          'enter_a_reason': 'Enter a reason',
          'please_pick': 'Please  pick a type',
          'apply': 'Apply',
          'reimbursement_details': 'Reimbursement details',
          'approval_pending': 'Approval pending',
          'claim_type': 'Claim type',
          'download_attachment': 'Download attachment',
          'delete': 'Delete',
          'cancel_reimbursement_request':
              'You are about to cancel the Reimbursement request.',
          'are_you_sure': 'Are you sure?',
          'leave_details': 'Leave Details',
          'applied_on': 'Applied on',
          'approved_on': 'Approved on',
          'approver': 'Approver',
          'cancel_leave': 'Cancel leave',
          '+91': '+91',
          'please_enter_reason': 'Please enter reason.',
          'leave_applied_successfully': 'Leave applied successfully',
          'no_leave_application_yet': 'No leave applications yet',
          'no_approved_leave_application_yet': 'No approved leave applications yet',
          'approval_successfully': 'Approved Successfully',
          'application_rejected': 'Application rejected',
          'disabled': 'Disabled',
          'absent': 'Absent',
          'present': 'Present',
          'leave': 'Leave',
          'resolve': 'Resolve',
          'attendance_not_available': 'Attendance not available',
          'you_are_about_to_cancel_the_leave_request':
              'You are about to cancel the leave request.',
          'company_documents': 'Company Documents',
          'my_documents': 'My Documents',
          'payslips': 'Payslips',
          'policies': 'Policies',
          'form_16': 'Form 16',
          'yes': 'Yes',
          'no': 'No',
          'leave_cancelled_successfully': 'Leave cancelled successfully',
          'day_application': 'Day application',
          'days_application': 'Days application',
          'leave_balance': 'Leave balance',
          'supporting_images_or_documents': 'Supporting images or documents',
          'maximum_mb_each': '(maximum 5MB each)',
          'choose_files': 'Choose file(s)..',
          'amount_requested': 'Amount Requested',
          'enter_valid_number': 'Enter Valid Number',
          'please_picks': 'Please pick',
          'claim_request_initiated_successfully':
              'Claim request initiated successfully',
          'no_reimbursement_application_yet': 'No reimbursements found',
          'we_regret_the_technical_error':
              'We regret the technical error. Please try again after some time.',
          'taking_selfie': 'Taking Selfie',
          'selfie_will_be_validated_against_the_picture':
              'Selfie will be validated against the picture that you have submitted during registration',
          'click_picture': 'Click Picture',
          'click_again': 'Click Again',
          'compressing_image': 'Compressing image...',
          'uploading': 'Uploading...',
          'submitting': 'Submitting...',
          'mark_as_leave': 'Mark as Leave',
          'regularise_now': 'Regularise Now',
          'date': 'Date',
          'punch_in_time_must_be_less_then_punch_out_time':
              'Punch in time must be less then punch out time.',
          'punch_out_time_must_be_greater_then_punch_in_time':
              'Punch out time must be greater then punch in time.',
          'regularisation': 'Regularisation',
          'regularisation_requested_successfully':
              'Regularisation requested successfully',
          'regularisation_initiated': 'Regularisation initiated:',
          'regularisation_details': 'Regularisation Details',
          'regularisation_cancelled_successfully':
              'Regularisation cancelled successfully',
          'you_are_about_to_cancel_the_regularisation_request':
              'You are about to cancel the regularisation request.',
          'regularisation_not_available': 'Regularisations not available',
          'edit_profile': 'Edit profile',
          'personal_details': 'Personal Details',
          'basic_details': 'Basic Details',
          'work_details': 'Work Details',
          'employee_name': 'Employee name',
          'employee_id': 'Employee id',
          'email_id': 'Email id',
          'gender': 'Gender',
          'contact_number': 'Contact number',
          'doj': 'DOJ',
          'type_of_employee': 'Type of employee',
          'team': 'Team',
          'reporting_manager': 'Reporting Manager',
          'shift': 'Shift',
          'days_pending_for_regularisation': 'Days Pending For Regularisation',
          'organisation_not_available': 'Organisation not available',
          'select_organisation': 'Select organisation',
          'continue': 'Continue',
          'manager': 'Manager',
          'rm_quick_actions': 'RM - Quick Actions',
          'claim_details': 'Claim details',
          'claim_number': 'Claim Number',
          'claim_amount': 'Claim Amount',
          'attachments': 'Attachments',
          'approve': 'Approve',
          'reject': 'Reject',
          'from_date_must_be_less_then_to_date':
              'From date must be less then to date',
          'to_date_must_be_greater_then_from_date':
              'To date must be greater then from date',
          'regularisations': 'Regularisations',
          'select_approvar': 'Select Approvar',
          'attendance_details': 'Attendance Details',
          'status': 'Status',
          'selfie': 'Selfie',
          'location': 'Location',
          'regular': 'Regular',
          'restricted': 'Restricted',
          'all_holiday': 'All Holidays',
          'restircted_holidays_balance': 'Restircted Holidays Balance',
          'no_faq_available': 'No FAQs found',
          'claim_approve': 'Claim -',
          'requested_amount': 'Requested Amount',
          'approved_amount': 'Approved Amount',
          'remark_optional': 'Remarks',
          'preview': 'Preview',
          'work_location': 'Work Location',
          'today': 'Today',
          'this_week': 'This week',
          'custom_date': 'Custom date',
          'clear_all': 'Clear All',
          'no_of_days': 'No. of Days',
          'leave_approved': 'Leave approved',
          'leave_rejected': 'Leave rejected',
          'no_leave_request_found': 'No leave request found',
          'you_want_to_mark_attendance': 'You want to mark attendance',
          'total_duration': 'Total duration',
          'half_day': 'Half day',
          'holidays_not_not_found': 'Holidays not found',
          'all_holidays': 'All Holidays',
          'regular_holidays': 'Regular Holidays',
          'restricted_holidays': 'Restricted Holidays',
          'holiday': 'Holiday',
          'Balance': 'balance',
          'regularise_date': 'Regularise Date',
          'no_document_found': 'No documents found',
          'okay': 'Okay',
          'attendance_summary': 'Attendance summary',
          'regularisation_summary': 'Regularisation summary',
          'leaves_summary': 'Leaves summary',
          'reimbursement_summary': 'Reimbursement summary',
          'request_pending': 'Request pending',
          'request_approved': 'Request approved',
          'request_rejected': 'Request rejected',
          'cancelled': 'Cancelled',
          'cancelled_leave': 'Cancelled Leave',
          'dob': 'DOB',
          'rejected_on': 'Rejected on',
          'weekly_off': 'Weekly Off',
          'regularisation_requested': 'Regularisation requested',
          'leave_requested': 'Leave requested',
          're_request': 'Re-Request',
          'canceled': 'Canceled',
          'canceled_leave': 'Canceled Leave',
          'no_claim_request_found': 'No claim requests found',
          'claim_no': 'Claim. No :',
          'claim': 'Claim :',
          'pdf': 'PDF',
          'app_update': 'App update?',
          'please_update_to_continue_using_the_app': 'Please update to continue using the app',
          'update': 'Update',
          'later': 'Later',
          'notification_not_available': 'Notification not available',
          'vendor_name': 'Vendor Name',
          'stay_date': 'Stay Date',
          'from_destination': 'From Destination',
          'stay_location': 'Stay Location',
          'to_destination': 'To Destination',
          'date_of_travel': 'Date Of Travel',
          'distance_travelled': 'Distance Travelled',
          'file_uploading_is_in_progress_please_wait': 'File uploading is in progress, please wait...',
          'claim_date': 'Claim Date',
          'comp_off': 'Comp-Off',
          'comp_off_balance': 'Comp-Off balance',
          'apply_comp_off': 'Apply Comp-Off',
          'no_comp_off_application_yet': 'No Comp-Off application yet',
          'no_approved_comp_off_application_yet': 'No Approved Comp-Off application yet',
          'comp_off_details': 'Comp-Off Details',
          'cancel_comp_off': 'Cancel Comp-Off',
          'you_are_about_to_cancel_the_comp_off_request': 'You are about to cancel the Comp-Off request',
          'comp_off_cancelled_successfully': 'Comp-Off cancelled successfully',
          'cancelled_comp_off': 'Cancelled Comp-Off',
          'apply_holiday': 'Apply holiday',
          'holiday_leave_applied_successfully': 'Holiday leave applied successfully',
          'comp_off_summary': 'Comp-Off Summary',
          'comp_off_request_not_available': 'Comp-Off request not available',
          'comp_off_accepted': 'Comp-Off accepted',
          'comp_off_rejected': 'Comp-Off rejected',
          'accept': 'accept',
          'task_fulfilment': 'Task Fulfilment',
          'you_are_not_in_your_work_location': 'You are not in your work location',
          'please_move_to_your_work_location_to_mark_attendance': 'Please move to your work location to mark attendance',
          'please_switch_on_your_phone_location_service': 'Please switch on your phone\'s location to mark your attendance.',
        },
        'hi': {
          'app_name': '',
          'server_error':
              'हमें तकनीकी त्रुटि के लिए खेद है। कृपया कुछ समय बाद पुन: प्रयास करें।',
          '': '',
        },
      };
}
