// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChzbZu7p42KayGfVpJ79yrsePHGpYGRK0',
    appId: '1:757214614937:web:d72ca1775db7e5f9ee6f08',
    messagingSenderId: '757214614937',
    projectId: 'hrms-production-6b12b',
    authDomain: 'hrms-production-6b12b.firebaseapp.com',
    storageBucket: 'hrms-production-6b12b.appspot.com',
    measurementId: 'G-PYWHWHNLBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1VOM1Fp6sE-8jNP0KvdPXnAD_DWq3_Kk',
    appId: '1:757214614937:android:8b52283a019fbdbbee6f08',
    messagingSenderId: '757214614937',
    projectId: 'hrms-production-6b12b',
    storageBucket: 'hrms-production-6b12b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSEVjIkJKMMfLVkVNMzJVwPRnykpfeQVk',
    appId: '1:757214614937:ios:63359bc8f0fbf08bee6f08',
    messagingSenderId: '757214614937',
    projectId: 'hrms-production-6b12b',
    storageBucket: 'hrms-production-6b12b.appspot.com',
    iosClientId: '757214614937-903s3ieksl2au3fhrdpot6k4en68rk64.apps.googleusercontent.com',
    iosBundleId: 'com.awign.saas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSEVjIkJKMMfLVkVNMzJVwPRnykpfeQVk',
    appId: '1:757214614937:ios:e590148255e4363aee6f08',
    messagingSenderId: '757214614937',
    projectId: 'hrms-production-6b12b',
    storageBucket: 'hrms-production-6b12b.appspot.com',
    iosClientId: '757214614937-odha95ahublo7ucfu5tr99t4ss1b04ia.apps.googleusercontent.com',
    iosBundleId: 'com.awign.saas.awignSaas.RunnerTests',
  );
}
